pub const INTERNAL_DISPLAY_WIDTH = 64;
pub const INTERNAL_DISPLAY_HEIGHT = 32;

pub const VRAM_SIZE = INTERNAL_DISPLAY_WIDTH * INTERNAL_DISPLAY_HEIGHT;

pub const DISPLAY_SCALE = 16;
pub const DISPLAY_WIDTH = INTERNAL_DISPLAY_WIDTH * DISPLAY_SCALE;
pub const DISPLAY_HEIGHT = INTERNAL_DISPLAY_HEIGHT * DISPLAY_SCALE;
pub const DISPLAY_REFRESH_RATE = 60;

pub const CLOCK_SPEED = 500;

pub const KEYPAD_SIZE = 16;

const NS_PER_US = 1000;
const NS_PER_MS = 1000 * NS_PER_US;
pub const NS_PER_S = 1000 * NS_PER_MS;
