pub const INTERNAL_DISPLAY_WIDTH = 64;
pub const INTERNAL_DISPLAY_HEIGHT = 32;

pub const VRAM_SIZE = INTERNAL_DISPLAY_WIDTH * INTERNAL_DISPLAY_HEIGHT;

pub const DEFAULT_DISPLAY_SCALE = 16;
pub const DISPLAY_REFRESH_RATE = 60;

pub const DEFAULT_FOREGROUND_COLOR = 0xFFFFFFFF;
pub const DEFAULT_BACKGROUND_COLOR = 0x000000FF;

pub const CLOCK_SPEED = 500;

pub const KEYPAD_SIZE = 16;

const NS_PER_US = 1000;
const NS_PER_MS = 1000 * NS_PER_US;
pub const NS_PER_S = 1000 * NS_PER_MS;

pub const DEFAULT_ADDRESS = "127.0.0.1";
pub const DEFAULT_PORT = 7890;
