pub const INTERNAL_DISPLAY_WIDTH = 64;
pub const INTERNAL_DISPLAY_HEIGHT = 32;
pub const VRAM_SIZE = INTERNAL_DISPLAY_WIDTH * INTERNAL_DISPLAY_HEIGHT;
pub const DISPLAY_SCALE = 16;
pub const DISPLAY_WIDTH = INTERNAL_DISPLAY_WIDTH * DISPLAY_SCALE;
pub const DISPLAY_HEIGHT = INTERNAL_DISPLAY_HEIGHT * DISPLAY_SCALE;
pub const KEYPAD_SIZE = 16;
